name: Build and Push Container images

env:
  IMAGE_REGISTRY: quay.io

on:
  workflow_run:
    workflows:
      - "Basic build and test"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.workflow_run.head_branch || github.event.ref || github.ref }}"
  cancel-in-progress: false

jobs:
  build-native-images:
    if: ${{ github.repository_owner == 'tqvarnst' && github.ref_name == 'main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    environment: QUAY
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        project:
          - flagstar-demo
        arch:
          - amd64

    name: "Build Native images (${{ matrix.arch}}-${{ matrix.project }}-java${{ matrix.java }})"
    steps:
      - name: Calculate Branch (workflow_run event)
        if: github.event_name == 'workflow_run'
        run: |
          echo "REF=${{ github.event.workflow_run.head_commit.id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Calculate Branch (workflow_dispatch event)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "REF=${{ github.sha }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "Quay username is ${{ secrets.QUAY_REPO_USERNAME }}"

      - name: Checkout from ${{ env.REF }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Login to quay
        uses: docker/login-action@v2
        if: ${{ github.repository_owner == 'tqvarnst' && github.ref_name == 'main' && github.event_name != 'pull_request' }}
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build native image (${{ matrix.project }}-java${{ matrix.java }}-${{ matrix.arch}})
        run: |
          ./mvnw -B clean package -DskipTests -Pnative -Dquarkus.profile=push



